# Generated by Django 5.1.3 on 2024-12-17 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cine', '0002_alter_actor_id_alter_cine_actor_alter_cine_director_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cine',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
